var products = {
  product: [
    {
      productId: 1,
      Name: "Krish",
      Catigories: "Lee",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 2,
      Name: "Krish",
      Catigories: "Drug",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 3,
      Name: "Krish",
      Catigories: "Drug",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 4,
      Name: "Krish",
      Catigories: "Drug",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 5,
      Name: "Krish",
      Catigories: "Drug",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 6,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 7,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 8,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 9,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
    {
      productId: 10,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "./images/img1.jpg",
    },
  ],
};
