var products = {
  product: [
    {
      productId: 1,
      Name: "Mucus DM",
      Catigories: "Lee",
      price: "$10.96",
      imageURL: "images/mucusdm.jpg",
      details: "GoodSense Maximum Strength Mucus DM Expectorant and Cough Suppressant",
    },
    {
      productId: 2,
      Name: "bob",
      Catigories: "Drug",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 3,
      Name: "sally",
      Catigories: "Drug",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 4,
      Name: "Krish",
      Catigories: "Drug",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 5,
      Name: "Krish",
      Catigories: "Drug",
      price: "123456",
      imageURL: "./images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 6,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 7,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 8,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 9,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
    {
      productId: 10,
      Name: "Krish",
      Catigories: "Cosmetic",
      price: "123456",
      imageURL: "images/img1.jpg",
      details: "sdfasdf",
    },
  ],
};
